# Generated by Django 5.2.7 on 2026-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerapplication",
            name="profession",
            field=models.CharField(
                choices=[
                    (
                        "Enfermeiro / Técnico de Enfermagem",
                        "Enfermeiro / Técnico de Enfermagem",
                    ),
                    ("Fisioterapeuta", "Fisioterapeuta"),
                    ("Psicólogo", "Psicólogo"),
                    ("Nutricionista", "Nutricionista"),
                    ("Assistente Social", "Assistente Social"),
                    ("Artesão / Professor de Artes", "Artesão / Professor de Artes"),
                    ("Comunicador / Social Media", "Comunicador / Social Media"),
                    ("Voluntário Geral", "Voluntário Geral"),
                ],
                default="Voluntário Geral",
                max_length=120,
            ),
        ),
    ]
